# workflow name
name: CML_Wine-Model-Quality
# specifying a trigger 
on: [push]
jobs:
  run:
    # run on ubuntu OS 
    runs-on: [ubuntu-latest]
    # using a CML project docker container
    container: docker://dvcorg/cml-py3:latest
    steps:
        # using a github action script
      - uses: actions/checkout@v2
        # naming the step
      - name: cml_run
        # checking credentials for authentication repo in secrets
        env:
          repo_token: ${{ secrets.GH_TOKEN }}
        # Your ML workflow
        run: |
          
          # installs the requirements in a docker container(Kubernetes can also be used)
          pip install -r requirements.txt
          
          # run the training script in the VE created using docker as a whole stack
          python train.py
          
          echo "MODEL METRICS"
          cat metrics.txt
